# Car Dataset Playground

In [19]:
import pandas as pd
from solution import add_virtual_column

### 1. Dataset

In [20]:
df_cars = pd.DataFrame({
    'make': ['Porsche', 'Ferrari', 'Lamborghini', 'McLaren', 'Aston Martin', 'Chevrolet'],
    'model': ['911 Turbo S', 'F8 Tributo', 'Huracan Evo', '720S', 'DBS Superleggera', 'Corvette Z06'],
    'base_price': [230000, 280000, 210000, 305000, 316000, 105000],
    'options_price': [45000, 60000, 35000, 75000, 25000, 15000],
    'dealer_discount': [5000, 0, 10000, 15000, 20000, 2000],
    'horsepower': [640, 710, 630, 710, 715, 670],
    'cylinders': [6, 8, 10, 8, 12, 8],
    'weight_lbs': [3636, 3164, 3135, 3128, 3733, 3434],
})
display(df_cars)

,make,model,base_price,options_price,dealer_discount,horsepower,cylinders,weight_lbs
0,Porsche,911 Turbo S,230000,45000,5000,640,6,3636
1,Ferrari,F8 Tributo,280000,60000,0,710,8,3164
2,Lamborghini,Huracan Evo,210000,35000,10000,630,10,3135
3,McLaren,720S,305000,75000,15000,710,8,3128
4,Aston Martin,DBS Superleggera,316000,25000,20000,715,12,3733
5,Chevrolet,Corvette Z06,105000,15000,2000,670,8,3434

### 2. Operation: Calculating Subtotal

In [21]:
df_step1 = add_virtual_column(
    df_cars, 
    "base_price + options_price - dealer_discount", 
    "subtotal"
)
display(df_step1)

,make,model,base_price,options_price,dealer_discount,horsepower,cylinders,weight_lbs,subtotal
0,Porsche,911 Turbo S,230000,45000,5000,640,6,3636,270000
1,Ferrari,F8 Tributo,280000,60000,0,710,8,3164,340000
2,Lamborghini,Huracan Evo,210000,35000,10000,630,10,3135,235000
3,McLaren,720S,305000,75000,15000,710,8,3128,365000
4,Aston Martin,DBS Superleggera,316000,25000,20000,715,12,3733,321000
5,Chevrolet,Corvette Z06,105000,15000,2000,670,8,3434,118000

### 3. Operation: Applying Sales Tax (Float Multiplication)

In [22]:
df_step2 = add_virtual_column(
    df_step1, 
    "subtotal + subtotal * 0.085", 
    "out_the_door_price"
)
display(df_step2[['make', 'model', 'subtotal', 'out_the_door_price']])

           make             model  subtotal  out_the_door_price
0       Porsche       911 Turbo S    270000            292950.0
1       Ferrari        F8 Tributo    340000            368900.0
2   Lamborghini       Huracan Evo    235000            254975.0
3       McLaren              720S    365000            396025.0
4  Aston Martin  DBS Superleggera    321000            348285.0
5     Chevrolet      Corvette Z06    118000            128030.0

### 4. Operation: Performance Score

In [23]:
df_step3 = add_virtual_column(
    df_step2, 
    "horsepower * cylinders - weight_lbs * 0.5", 
    "performance_score"
)
display(df_step3[['make', 'model', 'horsepower', 'cylinders', 'weight_lbs', 'performance_score']])

,make,model,horsepower,cylinders,weight_lbs,performance_score
0,Porsche,911 Turbo S,640,6,3636,2022.0
1,Ferrari,F8 Tributo,710,8,3164,4098.0
2,Lamborghini,Huracan Evo,630,10,3135,4732.5
3,McLaren,720S,710,8,3128,4116.0
4,Aston Martin,DBS Superleggera,715,12,3733,6713.5
5,Chevrolet,Corvette Z06,670,8,3434,3643.0